@startuml
'https://plantuml.com/class-diagram
'skinparam linetype polyline

class 森林

class 树 {
    高度(Height)
    层级(Level)
    深度(Depth)
    度(Degree)
    边(Edge)
}
class 子树 extends 树

class 节点{
    高度(Height)
    层级(Level)
    深度(Depth)
    度(Degree)
}

class 父节点 extends 节点
class 子节点 extends 节点
class 叶子节点 extends 节点
class 兄弟节点 extends 节点
class 内部节点 extends 节点

class 边
class 节点

森林 o--> 树:1:m(m>0)
树 o--> 节点:1:m(m≥0)
树 o--> 子树:1:m(m≥0)
树 o--> 边:1:n-1(n 是节点数)

@enduml