@startuml
'https://plantuml.com/class-diagram

package com.highzap.notification.wechat {

    class WeChatNotification implements Notification { }
    class WeChatChannelProvider implements ChannelProvider {}

    package com.highzap.notification.wechat.message{
         abstract class AbstractMessage implements Message {}
         class TextMessage extends AbstractMessage {}
         class Text{}

         TextMessage --> Text
    }
}

@enduml