@startuml
'https://plantuml.com/class-diagram

interface BudgetService {
    updateAmount(BusinessType type,BigDecimal amount,String budgetId,String subjectId,Integer month);// 更新预算金额
}


BudgetService ..> BusinessType: 依赖 >

enum BusinessType {
    MATTER, // 立项 MatterAmount、OccurAmount
    CONTRACT, // 合同 ContractAmount、OccurAmount(非立项合同需更新)
    SUPPLEMENT_CONTRACT, // 合同 ContractAmount、OccurAmount(非立项合同需更新)
    REIMBURSEMENT // ExpenseAmount、FactAmount、OccurAmount((非立项合同需更新)
}

@enduml