# UAA oauth2 client
highzap:
  security:
    oauth2:
      client:
        cdb:
          clientId: 785B30443FD6E2DE160408DDCFCAE6FA
          clientSecret: 785B30443FD6E2DE160408DDCFCAE6FA
# 微信配置信息
wechat:
  # 企业微信配置
  corp:
    corpId: ww13e9492fe4b02153
    # 企业微信应用配置
    corpapp:
      cdb:
        agentId: 1000002
        secret: dsq1HWzRkcJ27VxrC8gRsTXu17Kq39LlJIY5kk3w-g4
        token: xx
        encodingAESKey: xx
# 钉钉应用配置
dingtalk:
  corpId: ww13e9492fe4b02153
  # H5 微应用
  corph5:
    cdb:
      agentId: 839623199
      appKey: dinguwg6g6mthlnl2p52
      appSecret: tC4M5s6WImzZFUVolwDOVL_fpK9bOgEpAL9-DN23QisVLInPEx8YdejUL4KLC9Sc
  # 小程序
  corpeapp:
    cdb:
      agentId: 841699991
      appKey: dingapfeqfjbyjq4joiv
      appSecret: rudlSmgPuDqKYGxxSzL2M1a0Z47YzSlbB8eiGICyRfmrhTLqaURnnGmnZxzd_doC
  # 扫码登录应用
  loginman:
    cdb:
      appId: dingoakmulh1ut9nyk6kx4
      appSecret: U0U-9P9FA1iXl-OljiVJkd_MKxnOLiF6LZ03KGccxdmrwGDevS-hKB3NrEfwgujr

spring:
  datasource:
    hikari:
      ## 最小空闲连接数
      minimum-idle: 2
      ## 连接池最大连接数
      maximum-pool-size: 10
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名称
      pool-name: MyHikariCP
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 3000
    url: jdbc:mysql://127.0.0.1:3306/springboot-db?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
#  开启所有的 actuator 端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#info:
#  app:
#    version: "@project.version@"
#    encoding: "@project.build.sourceEncoding@"
#    java:
#      source: "@java.version@"
#      target: "@java.version@"
