@startuml

interface UserService{
    boolean save();
}

class UserServiceImpl {
    private UserDao userDao;
    public boolean save();
}

class UserDao {
    boolean insert();
}
UserService <|.. UserServiceImpl : 实现

UserDao  <-- UserServiceImpl : 关联

@enduml