# https://www.h2database.com/html/quickstart.html
spring:
  datasource:
    url: jdbc:h2:~/h2/test
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
#    data: classpath:db/mysql.sql
    platform: h2
    username: sa
    password: 123456
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true